apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: your-namespace
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <match **>
      @type your_log_management_tool
      api_key your_api_key
      host your_host
      port your_port
      secure yes
      <buffer>
        flush_interval 5s
      </buffer>
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: your-namespace
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.14.3-debian-1.0
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
          subPath: fluent.conf
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
