apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: your-namespace
spec:
  serviceName: postgresql
  replicas: 1   # Adjust as needed
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_DB
          value: your_database_name
        - name: POSTGRES_USER
          value: your_database_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-passwords
              key: postgresql-password
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi   # Adjust storage size as needed
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: your-namespace
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
