apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: your-app-monitor
  namespace: your-namespace
spec:
  selector:
    matchLabels:
      app: your-app
  endpoints:
  - port: web   # Assuming this is your service port name
    interval: 30s   # Adjust as per your monitoring needs
    path: /metrics  # Path to your service metrics endpoint
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: your-namespace
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    port: 9090
    targetPort: 9090
