apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: message-api-role-binding
subjects:
  - kind: ServiceAccount
    name: message-api-service-account
roleRef:
  kind: Role
  name: message-api-role
  apiGroup: rbac.authorization.k8s.io
